version: '3.4'

services:

  sampleprojectdb:
    image: mcr.microsoft.com/mssql/server

  sampleproject.api:
    image: ${DOCKER_REGISTRY-}sampleprojectapi
    build:
      context: .
      dockerfile: SampleProject.API/Dockerfile

  prometheus:
    image: prom/prometheus

  grafana:
    image: grafana/grafana

  redis:
    image: redis

  redisinsight:
    image: redislabs/redisinsight

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch